cvm-version: 0.7.5
cpus: 32
gpus: 8
memory: 524288

models:
  - name: "kimi-k2-6"
    repo: "moonshotai/Kimi-K2.6@2b2b88e33c96d813ebb4c83a740252fe08018e3a"
    mpk: "b9a191a313479bccc692491d74803b2520ae28c90bc440f9c76459d297529956_595205046272_1ea57052-e386-5369-8c4f-853663460858"

containers:
  - name: "kimi-k2-6"
    image: "vllm/vllm-openai:v0.19.1-cu130@sha256:cd7bf919c600a1d7f7312082e9406dd2cbc08024339136d8765dddadc65751ed"
    runtime: nvidia
    gpus: all
    ipc: host
    command: [
      "--model", "/tinfoil/mpk/mpk-b9a191a313479bccc692491d74803b2520ae28c90bc440f9c76459d297529956",
      "--tensor-parallel-size", "8",
      "--mm-encoder-tp-mode", "data",
      "--served-model-name", "kimi-k2-6",
      "--enable-auto-tool-choice",
      "--enable-prompt-tokens-details",
      "--tool-call-parser", "kimi_k2",
      "--reasoning-parser", "kimi_k2",
      "--trust-remote-code",
      "--port", "8001",
      "--scheduling-policy", "priority",
    ]

shim:
  upstream-port: 8001
  authenticated: true
  authenticated-endpoints:
    - /v1/chat/completions
  paths:
    - /v1/chat/completions
    - /metrics
    - /health
